name: Integration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '^8.1'

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run integration test
      run: vendor/bin/phpunit tests/Integration/IntegrationTest.php
